const marvelDatabase = [
  // THE INFINITY SAGA (MCU PHASE 1 & 2)
  {id:1, universe:"mcu", title:"Iron Man", year:2008, tag:"🐐 ONE OF THE LEGENDS", type:"legend", mine:true, rating:9.5, note:"This is where everything begins. I REALLY want you to tell me what you think about Tony.", fact:"Robert Downey Jr. became one of the most important casting choices in the MCU's history.", symbol:"◉"},
  {id:2, universe:"mcu", title:"The Incredible Hulk", year:2008, tag:"😐 MEH… BUT WE MOVE", type:"meh", mine:false, rating:5.5, note:"Not my favourite, but we're committed to the mission.", fact:"Edward Norton played Bruce Banner before Mark Ruffalo eventually took over the role.", symbol:"◆"},
  {id:3, universe:"mcu", title:"Iron Man 2", year:2010, tag:"❤️ WATCH WITH ME", type:"mine", mine:true, rating:7, note:"There are things in here you'll appreciate later. Trust me.", fact:"Iron Man 2 helped introduce Black Widow and expanded the connections leading toward The Avengers.", symbol:"✦"},
  {id:4, universe:"mcu", title:"Thor", year:2011, tag:"👀 PAY ATTENTION", type:"important", mine:false, rating:7.5, note:"Meet someone who becomes VERY important.", fact:"Kenneth Branagh directed Thor and brought a Shakespearean sensibility to Asgard.", symbol:"⌁"},
  {id:5, universe:"mcu", title:"Captain America: The First Avenger", year:2011, tag:"💖 PLEASE WATCH FOR ME", type:"mine", mine:true, rating:8.5, note:"This one has a special place in my Marvel brain.", fact:"Chris Evans initially hesitated to accept the role of Captain America.", symbol:"✚"},
  {id:6, universe:"mcu", title:"The Avengers", year:2012, tag:"🔥 YOU MADE IT", type:"legend", mine:true, rating:9, note:"Okay. NOW it starts getting serious.", fact:"The Avengers became the first Marvel Studios movie to cross $1 billion worldwide.", symbol:"A"},
  {id:7, universe:"mcu", title:"Iron Man 3", year:2013, tag:"😂 JUST WATCH IT", type:"fun", mine:false, rating:7, note:"Don't Google anything beforehand.", fact:"Iron Man 3 was the first Marvel Studios film released after The Avengers.", symbol:"◉"},
  {id:8, universe:"mcu", title:"Thor: The Dark World", year:2013, tag:"💀 GOOD LUCK", type:"meh", mine:false, rating:5, note:"We have to suffer together.", fact:"Much of the movie's production took place in and around London.", symbol:"⌁"},
  {id:9, universe:"mcu", title:"Captain America: The Winter Soldier", year:2014, tag:"🐐 ABSOLUTE LEGEND", type:"legend", mine:true, rating:9.5, note:"One of the ones I am MOST excited for you to see.", fact:"The film was deliberately shaped like a political conspiracy thriller.", symbol:"✚"},
  {id:10, universe:"mcu", title:"Guardians of the Galaxy", year:2014, tag:"❤️ YOU NEED TO SEE THIS", type:"mine", mine:true, rating:9, note:"Please report your favourite Guardian immediately.", fact:"Before the movie, many audiences knew very little about the Guardians.", symbol:"🚀"},
  {id:11, universe:"mcu", title:"Avengers: Age of Ultron", year:2015, tag:"👀 PAY ATTENTION", type:"important", mine:false, rating:7.5, note:"Things are about to get MUCH bigger.", fact:"The film introduced several characters who became major parts of the MCU.", symbol:"A"},
  {id:12, universe:"mcu", title:"Ant-Man", year:2015, tag:"🐜 FUN ONE", type:"fun", mine:false, rating:7.5, note:"Tiny man. Big responsibilities.", fact:"Ant-Man had been in development at Marvel for many years.", symbol:"🐜"},

  // SONY SPIDER-VERSE
  {id:101, universe:"sony", title:"Spider-Man", year:2002, tag:"🕸️ CLASSIC", type:"fun", mine:true, rating:8.5, note:"The Tobey Maguire era begins.", fact:"The upside-down kiss is iconic.", symbol:"🕸"},
  {id:102, universe:"sony", title:"Spider-Man 2", year:2004, tag:"🐐 MASTERPIECE", type:"legend", mine:true, rating:9.5, note:"Doc Ock is one of the greatest villains ever.", fact:"Alfred Molina's mechanical tentacles were practical puppets.", symbol:"🐙"},
  {id:103, universe:"sony", title:"Spider-Man 3", year:2007, tag:"🕺 EMO PETER", type:"fun", mine:false, rating:6.5, note:"Get ready for some highly questionable dance moves.", fact:"The studio forced director Sam Raimi to include Venom.", symbol:"🕷"},
  {id:104, universe:"sony", title:"The Amazing Spider-Man", year:2012, tag:"🛹 SKATER VIBES", type:"fun", mine:false, rating:7.5, note:"Andrew Garfield's take on the character.", fact:"Emma Stone and Andrew Garfield met and started dating on this set.", symbol:"🕸"},
  {id:105, universe:"sony", title:"The Amazing Spider-Man 2", year:2014, tag:"💔 EMOTIONAL", type:"important", mine:true, rating:7.0, note:"The chemistry is unmatched. Prepare yourself.", fact:"Hans Zimmer composed the incredible Electro theme.", symbol:"⚡"},

  // FOX MUTANT SAGA
  {id:201, universe:"fox", title:"X-Men", year:2000, tag:"❌ THE START", type:"important", mine:false, rating:7.5, note:"The movie that kicked off the modern superhero craze.", fact:"Hugh Jackman was cast as Wolverine very late in production.", symbol:"X"},
  {id:202, universe:"fox", title:"X2: X-Men United", year:2003, tag:"🔥 TOP TIER", type:"legend", mine:true, rating:8.5, note:"The Nightcrawler White House opening is pure cinema.", fact:"It is widely considered one of the best superhero sequels.", symbol:"X"},
  {id:203, universe:"fox", title:"X-Men: The Last Stand", year:2006, tag:"💀 CHAOS", type:"meh", mine:false, rating:5.0, note:"A lot happens. Maybe too much.", fact:"Brett Ratner took over directing after Bryan Singer left for Superman Returns.", symbol:"X"},
  {id:204, universe:"fox", title:"X-Men: First Class", year:2011, tag:"✨ GROOVY", type:"fun", mine:true, rating:8.0, note:"The 1960s aesthetic is amazing. Magneto's origin is incredible.", fact:"Matthew Vaughn directed this stylish reboot prequel.", symbol:"X"},
  {id:205, universe:"fox", title:"X-Men: Days of Future Past", year:2014, tag:"🐐 TIME TRAVEL", type:"legend", mine:true, rating:9.0, note:"The best X-Men movie. The Quicksilver scene is legendary.", fact:"It merged the original cast with the First Class prequel cast.", symbol:"⏳"}
];
